spring:
  datasource:
    url: jdbc:h2:~/steward.db
    username: a
    password: a
  h2:
    
    console:
      enabled: true
      path: /h2-console
      
#  security: 
#    user:
#      password: password
#    oauth2:
#      client:
#        client-id: client
#        client-secret: secret

---
spring:
  profiles : maria
  
---
spring:
  profiles : prod
  h2:
    console:
      enabled: false
  
#  spring.datasource.url=jdbc:mariadb://localhost:3306/stewarddb
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=create-drop
